# Generated by Django 3.2.8 on 2021-12-24 07:02

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import stories_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryShare',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('original_caption', models.TextField()),
                ('updated_caption', models.TextField()),
                ('agent', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users_app.users')),
            ],
        ),
        migrations.CreateModel(
            name='StoryComment',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('original_content', models.TextField()),
                ('updated_content', models.TextField()),
                ('agent', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users_app.users')),
            ],
        ),
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('story_cover', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('chapter', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('original_content', models.TextField()),
                ('updated_content', models.TextField(blank=True, null=True)),
                ('price', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('engagement', djongo.models.fields.EmbeddedField(model_container=stories_app.models.StoryEngagement, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('author', djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='users_app.users')),
                ('co_author', djongo.models.fields.ArrayReferenceField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_author', to='users_app.users')),
                ('users_comment', djongo.models.fields.ArrayReferenceField(null=True, on_delete=django.db.models.deletion.CASCADE, to='stories_app.storycomment')),
                ('users_like_list', djongo.models.fields.ArrayReferenceField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_like_list', to='users_app.users')),
                ('users_share', djongo.models.fields.ArrayReferenceField(null=True, on_delete=django.db.models.deletion.CASCADE, to='stories_app.storyshare')),
                ('users_view_list', djongo.models.fields.ArrayReferenceField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_view_list', to='users_app.users')),
            ],
        ),
    ]
