# Generated by Django 3.1.12 on 2021-12-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_user_verified',
            field=models.BooleanField(default=False),
        ),
    ]
